 /**
   CMP1 Generated Driver File
 
   @Company
     Microchip Technology Inc.
 
   @File Name
     cmp1.c
 
   @Summary
     This is the generated driver implementation file for the CMP1 driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
 
   @Description
     This source file provides implementations for driver APIs for CMP1.
     Generation Information :
         Product Revision  :  PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.0
         Device            :  PIC18F16Q41
         Driver Version    :  2.11
     The generated drivers are tested against the following:
         Compiler          :  XC8 2.10 and above or later
         MPLAB             :  MPLAB X 5.35
 */ 

 /*
    (c) 2018 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
*/
 
 /**
   Section: Included Files
 */


#include <xc.h>
#include "cmp1.h"

#include "../peakDetector.h"
#include "./pin_manager.h"
#include "adcc.h"
/**
  Section: CMP1 APIs
*/

void CMP1_Initialize(void)
{
    /* Disable CMP1 interrupt before configuring the CMP1
       control register. Although a comparator is disabled, an interrupt can be
       generated by changing the output polarity with the CxPOL bit of the
       CMxCON0 register,or by switching the comparator on or off with the CxON
       bit of the CMxCON0 register.*/
    PIE1bits.C1IE = 0;

	// C1HYS enabled; C1EN enabled; C1POL inverted; C1SYNC asynchronous;                          
    CM1CON0 = 0x92;
	
	// C1INTN intFlag_neg; C1INTP intFlag_pos;                          
    CM1CON1 = 0x03;
	
	// NCH CIN2-;                          
    CM1NCH = 0x02;
	
	// PCH DACOUT;                          
    CM1PCH = 0x05;
	
    // Clearing IF flag before enabling the interrupt.
    PIR1bits.C1IF = 0;

    // Enabling CMP1 interrupt.
    PIE1bits.C1IE = 1;
}

bool CMP1_GetOutputStatus(void)
{
	return (CM1CON0bits.C1OUT);
}

void CMP1_ISR(void)
{
    if (CM1CON1bits.INTP)
    {
        CM1CON1bits.INTP = 0;
        CM1CON1bits.INTN = 1;

        WindowOpen_LED_LAT = 1;          // Turn on an LED
        setState(PK_OPEN);               // Indicate the window is open
        ADSTPT = 0x00;                   // Clear the max
        ADCC_StartConversion(OpAmp_OUT);
    }
    else
    {
        CM1CON1bits.INTN = 0;
        CM1CON1bits.INTP = 1;
        
        WindowOpen_LED_LAT = 0;         // Turn off an LED
        ADCC_StopConversion();          // Abort the conversion
        setState(PK_DONE);              // Indicate that the peak can be printed now
    }
    // Clear the CMP1 interrupt flag
    PIR1bits.C1IF = 0;
}

/**
 End of File
*/
